"""Built-in SMB category list used to enumerate a region in grid mode.
Editable per country — this is the completeness dial."""

from __future__ import annotations

DEFAULT_CATEGORIES: list[str] = [
    "restaurant",
    "cafe",
    "bar",
    "bakery",
    "hairdresser",
    "barber shop",
    "beauty salon",
    "nail salon",
    "plumber",
    "electrician",
    "carpenter",
    "painter",
    "roofer",
    "cleaning service",
    "landscaper",
    "garden center",
    "car repair",
    "car wash",
    "auto parts store",
    "dentist",
    "physiotherapist",
    "veterinarian",
    "florist",
    "butcher",
    "greengrocer",
    "clothing store",
    "shoe store",
    "jeweler",
    "optician",
    "pharmacy",
    "pet store",
    "bookstore",
    "hardware store",
    "furniture store",
    "bike shop",
    "tailor",
    "dry cleaner",
    "photographer",
    "driving school",
    "real estate agency",
    "accountant",
    "law firm",
    "travel agency",
    "gym",
    "yoga studio",
    "tattoo parlor",
]

# Curated high-value subset for country-wide fan-out: independent trades, food,
# and personal services with high no-website rates. Drops website-saturated /
# regulated / chain categories (pharmacy, optician, dentist, law firm, accountant,
# real estate, travel agency, gym, etc.). The volume vs completeness dial.
CURATED_CATEGORIES: list[str] = [
    "restaurant",
    "cafe",
    "bar",
    "bakery",
    "hairdresser",
    "barber shop",
    "beauty salon",
    "nail salon",
    "plumber",
    "electrician",
    "carpenter",
    "painter",
    "roofer",
    "cleaning service",
    "landscaper",
    "car repair",
    "florist",
    "butcher",
    "photographer",
    "driving school",
    "tattoo parlor",
    "tailor",
    "dry cleaner",
    "bike shop",
]
