/**
 * lib/cms.ts — CMS fetch helpers
 *
 * Copy this file into your client website's lib/ directory.
 * Import cmsConfig from your cms.config.ts (or cms.config.json).
 *
 * Supports three usage patterns:
 *
 *  1. Next.js App Router (SSR + ISR):
 *       import { getCMSContent } from '@/lib/cms'
 *       const cms = await getCMSContent()   // ISR: revalidates every 60 s
 *
 *  2. React / Vite (CSR hook):
 *       import { useCMSContent } from '@/lib/cms'
 *       const { data: cms } = useCMSContent()
 *
 *  3. Astro / any SSR (fresh fetch):
 *       import { getCMSContentFresh } from '@/lib/cms'
 *       const cms = await getCMSContentFresh()
 *
 * Run `npm run cms:sync-types` to regenerate TypeScript types from the CMS.
 */

import { cmsConfig } from "../cms.config";
import type { CMSContent } from "../cms.types"; // generated by npm run cms:sync-types

/**
 * Resolve the CMS URL at build/run time.
 *
 * Priority:
 *  1. Build-time env var — `VITE_CMS_ENDPOINT` (Vite), `NEXT_PUBLIC_CMS_ENDPOINT` (Next.js),
 *     or `PUBLIC_CMS_ENDPOINT` (Astro). These are set by the CMS onboarding agent and
 *     already contain the full URL including the project slug (and `/draft` for preview
 *     deployments), so we use them as-is.
 *  2. Otherwise, fall back to `cmsConfig.endpoint + "/" + projectSlug`.
 *
 * This lets production and preview deployments point at different CMS endpoints
 * (published vs. draft) while local dev still picks up `cms.config.json`.
 */
function resolveCmsUrl(): string {
    const envUrl =
        // Vite (import.meta.env.*). Wrapped so non-Vite bundlers don't choke.
        (typeof import.meta !== "undefined" && (import.meta as unknown as { env?: Record<string, string> }).env?.VITE_CMS_ENDPOINT) ||
        // Next.js + Astro
        (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_CMS_ENDPOINT) ||
        (typeof process !== "undefined" && process.env?.PUBLIC_CMS_ENDPOINT) ||
        "";
    if (envUrl) return envUrl;
    return `${cmsConfig.endpoint}/${cmsConfig.projectSlug}`;
}

function resolvePreviewToken(): string | null {
    return (
        (typeof import.meta !== "undefined" && (import.meta as unknown as { env?: Record<string, string> }).env?.VITE_CMS_PREVIEW_TOKEN) ||
        (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_CMS_PREVIEW_TOKEN) ||
        (typeof process !== "undefined" && process.env?.PUBLIC_CMS_PREVIEW_TOKEN) ||
        null
    );
}

const CMS_URL = resolveCmsUrl();
const PREVIEW_TOKEN = resolvePreviewToken();

function cmsHeaders(extra: Record<string, string> = {}): Record<string, string> {
    const headers: Record<string, string> = { Accept: "application/json", ...extra };
    if (PREVIEW_TOKEN) headers["X-CMS-Preview-Token"] = PREVIEW_TOKEN;
    return headers;
}

// ── Async fetch helpers ───────────────────────────────────────────────────────

/**
 * Fetches all public content for this project.
 * Next.js ISR: revalidates every 60 seconds (matches CMS Cache-Control header).
 * On other runtimes, behaves the same as getCMSContentFresh().
 */
export async function getCMSContent(): Promise<CMSContent> {
    const res = await fetch(CMS_URL, {
        // Next.js ISR: revalidate every 60 s
        next: { revalidate: 60 },
        headers: cmsHeaders(),
    } as RequestInit);

    if (!res.ok) {
        throw new Error(`CMS fetch failed: ${res.status} ${res.statusText} — ${CMS_URL}`);
    }

    return res.json() as Promise<CMSContent>;
}

/**
 * Fetches content with no caching (guaranteed fresh data).
 * Use in development, Astro SSR, or API route handlers.
 */
export async function getCMSContentFresh(): Promise<CMSContent> {
    const res = await fetch(CMS_URL, {
        cache: "no-store",
        headers: cmsHeaders(),
    });

    if (!res.ok) {
        throw new Error(`CMS fetch failed: ${res.status} ${res.statusText} — ${CMS_URL}`);
    }

    return res.json() as Promise<CMSContent>;
}

// ── React hook (React / Vite CSR only) ───────────────────────────────────────
// Only import this in React projects. Do not use in SSR / server components.

let _cache: { data: CMSContent; fetchedAt: number } | null = null;
const CACHE_TTL_MS = 60_000; // 60 s — matches CMS Cache-Control max-age

/**
 * React hook: fetches CMS content client-side with a 60-second module cache.
 * Returns { data, loading, error }.
 *
 * Falls back gracefully — if the CMS is unreachable, data stays null and
 * the caller should fall back to hard-coded constants with withFallback().
 *
 * @example
 *   const { data: cms } = useCMSContent()
 *   const title = withFallback(cms?.content.hero?.title, FALLBACK_TITLE)
 */
export function useCMSContent(): { data: CMSContent | null; loading: boolean; error: string | null } {
    // Dynamic import guards against bundling React into SSR builds
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { useState, useEffect, useRef } = require("react") as typeof import("react");

    const isFresh = _cache !== null && Date.now() - _cache.fetchedAt < CACHE_TTL_MS;
    const [data, setData] = useState<CMSContent | null>(_cache?.data ?? null);
    const [loading, setLoading] = useState(!isFresh);
    const [error, setError] = useState<string | null>(null);
    const fetchedRef = useRef(false);

    useEffect(() => {
        if (_cache !== null && Date.now() - _cache.fetchedAt < CACHE_TTL_MS) {
            setData(_cache.data);
            setLoading(false);
            return;
        }
        if (fetchedRef.current) return;
        fetchedRef.current = true;

        getCMSContentFresh()
            .then((cms) => {
                _cache = { data: cms, fetchedAt: Date.now() };
                setData(cms);
                setError(null);
            })
            .catch((err: unknown) => {
                setError(err instanceof Error ? err.message : "CMS fetch failed");
            })
            .finally(() => setLoading(false));
    }, []);

    return { data, loading, error };
}

// ── Utility helpers ───────────────────────────────────────────────────────────

/**
 * Returns a specific service's content from the CMS response.
 *
 * @example
 *   const hero = getService(cms, 'hero')
 *   console.log(hero?.title)
 */
export function getService<K extends keyof CMSContent["content"]>(
    cms: CMSContent | null,
    key: K
): CMSContent["content"][K] | undefined {
    return cms?.content[key];
}

/**
 * Returns the live CMS value, or the fallback if the CMS data is absent.
 * Use this to keep client websites functional even when the CMS is unreachable.
 *
 * @example
 *   const name = withFallback(cms?.content.cv?.entries?.name, CV_DATA.name)
 */
export function withFallback<T>(live: T | null | undefined, fallback: T): T {
    return live ?? fallback;
}
